# Generated by Django 5.2 on 2025-10-28 09:45

import greenkart.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenkart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', greenkart.models.UserManager()),
            ],
        ),
    ]
